### ISSUE TITLE
minor underline shows after paper button in <a> tag if space left between close tags in case of multiple buttons

### ISSUE THREAD

**Issue by vikjung** [Polymer/paper-button#15]
<a href="/home" ><paper-button label="Sign In" id="signin" ></paper-button> </a>

If there are two paper buttons within <a> tags next to each other and a space is left between the </paper-button> and </a> then a small underline shows after the buttons before the last one.

Another e.g. of issue is visible in the polymer site element collections page http://www.polymer-project.org/docs/elements/

point on the second docs button for Paper element section and will see the underline.

**Comment by ssorallen** [comment]
Just like it's weird to do this:

```html
<button>
  <a href="https://www.google.com">Google</a>
</button>
```

It should feel weird to do that with paper elements as well. If we want to style anchors like buttons, I think the base element should be an anchor. This could be another paper element:

```html
<a is="paper-button-anchor" href="https://www.google.com">Google</a>
```
